---
title: "data-preprocessing-data-banjir-jakarta-2023_2020"
output:
  html_document:
    df_print: paged
---
#Install Library
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(skimr)
library(DataExplorer)
library(tidyr)
library(dplyr)
library(summarytools)
```

#Read Data
```{r}
df <- read.csv(file="https://raw.githubusercontent.com/ali-murtadho/tsa-ml-project/master/combined%20(2).csv", header = T, sep = ",")
#str(df)
```
#Summary Data
```{r}
summary(df)
```

```{r}
skim(df)
```

#Describe data awal
```{r}
# Menampilkan nama kolom
cat("============= Kolom =============\n")
colnames(df)
cat("=================================\n")

# Menampilkan dimensi data
cat("============= Dimensi =============\n")
dim(df)
cat("=================================\n")

# Menampilkan statistik deskriptif untuk kolom numerik
cat("============= Describe Numerik =============\n")
summary(df)
cat("=================================\n")

# Menampilkan statistik deskriptif untuk kolom kategorik
cat("============= Describe Kategorik =============\n")
dfSummary(df)
cat("=================================\n")

# Menampilkan jumlah missing data per kolom
cat("============= Missing Data =============\n")
colSums(is.na(df))
cat("=================================\n")

# Menampilkan tipe data setiap kolom
cat("============= Tipe data =============\n")
sapply(df, class)
cat("=================================\n")

# Menampilkan jumlah nilai unik per kolom
cat("============= Kolom Unik =============\n")
for (kolom in colnames(df)) {
  banyak_unik <- length(unique(df[[kolom]]))
  nilai_unik <- unique(df[[kolom]])
  cat(sprintf('"%s": %d\n', kolom, banyak_unik))
  cat(sprintf('%s\n\n', toString(nilai_unik)))
}
cat("=================================\n")
```
#Missing Values
```{r}
print(colSums(is.na(df)))
```
```{r}

```

#Inisialisasi Missing values
```{r}
# Mengisi missing value dengan nilai 0 pada kolom "jumlah_meninggal"
df$jumlah_meninggal[is.na(df$jumlah_meninggal)] <- 0

# Mengisi missing value dengan nilai 0 pada kolom "jumlah_luka_ringan"
df$jumlah_luka_ringan[is.na(df$jumlah_luka_ringan)] <- 0

# Mengisi missing value dengan nilai 0 pada kolom "jumlah_luka_berat"
df$jumlah_luka_berat[is.na(df$jumlah_luka_berat)] <- 0

# Mengisi missing value dengan nilai 0 pada kolom "jumlah_tempat_pengungsian"
df$jumlah_tempat_pengungsian[is.na(df$jumlah_tempat_pengungsian)] <- 0

# Mengisi missing value dengan nilai 0 pada kolom "lama_genangan"
df$lama_genangan[is.na(df$lama_genangan)] <- 0

# Mengisi data pada kolom "a" yang berisi "" dengan "0"
df$ketinggian_air <- replace(df$ketinggian_air, df$ketinggian_air == "", "0")


```

# CLEANING KOLOM KETINGGIAN AIR
```{r}
print(sum(df$ketinggian_air == ""))
print(sum(df$ketinggian_air == "0"))
print(sum(df$ketinggian_air == " 10 - 40"))
```
```{r}
unique(df$ketinggian_air)
```

```{r}
# Menampilkan data yang memuat kata "" pada kolom "ketinggian air"
count(df[grep("\\,", df$ketinggian_air), ])
print(df[grep("\\,", df$ketinggian_air), ])
```

```{r}
# Replace Anomali data ketinggian air
df$ketinggian_air <- gsub("^(\\d+)-(\\d+).*", "\\1-\\2", df$ketinggian_air)
df$ketinggian_air <- gsub("^(\\d+).*-(\\d+).*", "\\1-\\2", df$ketinggian_air)
df$ketinggian_air <- gsub("19\\,22", "19", df$ketinggian_air)
df$ketinggian_air <- gsub("16\\,19", "16", df$ketinggian_air)
df$ketinggian_air <- gsub("17\\,19", "17", df$ketinggian_air)
df$ketinggian_air <- gsub("21\\,25", "21", df$ketinggian_air)
df$ketinggian_air <- gsub("17\\,19", "17", df$ketinggian_air)
df$ketinggian_air <- gsub("14\\,21", "14-21", df$ketinggian_air)
df$ketinggian_air <- gsub("24\\,26", "24-26", df$ketinggian_air)
df$ketinggian_air <- gsub("16\\,24", "16", df$ketinggian_air)
df$ketinggian_air <- gsub("19\\,25", "19", df$ketinggian_air)
df$ketinggian_air <- gsub("19\\,21", "19", df$ketinggian_air)
df$ketinggian_air <- gsub("16\\,21", "16", df$ketinggian_air)
df$ketinggian_air <- gsub("-\\(3Hari\\)|-\\(2Hari\\)|-\\(1Hari\\)", "", df$ketinggian_air)
df$ketinggian_air <- gsub("s/d", "-", df$ketinggian_air)
df$ketinggian_air <- gsub("s.d.", "-", df$ketinggian_air)
df$ketinggian_air <- gsub("\n", "-", df$ketinggian_air)
df$ketinggian_air <- gsub("cm", "", df$ketinggian_air)
df$ketinggian_air <- gsub(" ", "", df$ketinggian_air)
df$ketinggian_air <- gsub("S/D", "-", df$ketinggian_air)
df$ketinggian_air <- gsub("sm", "", df$ketinggian_air)
df$ketinggian_air <- gsub("-\\(3Hari\\)|-\\(2Hari\\)|-\\(1Hari\\)", "", df$ketinggian_air)
df$ketinggian_air <- gsub("-\\(4Hari\\)|-\\(5Hari\\)|-\\(7Hari\\)|-\\(6Hari\\)", "", df$ketinggian_air)
df$ketinggian_air <- gsub("-\\(8Hari\\)|-\\(13Hari\\)|-\\(10Hari\\)|-\\(9Hari\\)", "", df$ketinggian_air)

```

```{r}
#melihat hasil pembersihan
unique(df$ketinggian_air)
```

```{r}
# Membuat kolom baru "ketinggian_air_minimal" dan "ketinggian_air_maksimal"
df$ketinggian_air_minimal <- NA
df$ketinggian_air_maksimal <- NA

# Memisahkan data dalam kolom "ketinggian_air"
for (i in 1:nrow(df)) {
  if (grepl("-", df$ketinggian_air[i])) {
    range <- unlist(strsplit(df$ketinggian_air[i], "-"))
    df$ketinggian_air_minimal[i] <- as.numeric(range[1])
    df$ketinggian_air_maksimal[i] <- as.numeric(range[2])
  } else {
    df$ketinggian_air_minimal[i] <- as.numeric(df$ketinggian_air[i])
    df$ketinggian_air_maksimal[i] <- as.numeric(df$ketinggian_air[i])
  }
}

# Menampilkan hasil
head(df$ketinggian_air)

```
```{r}
#Pembuatan kolom agregasi Average Ketinggian air minimal
df$avg_ketinggian_air <- (df$ketinggian_air_minimal + df$ketinggian_air_maksimal) / 2
```


# Penggabungan kolom bulan dan tahun
```{r}
#install.packages("lubridate")

library(lubridate)

# Membuat kolom "date" dengan format "month-year"
df$date <- as.Date(paste(df$tahun, df$bulan, "01", sep = "-"), format = "%Y-%m-%d")
df$date <- format(df$date, "%m-%Y")

```


#Cleaning RW
```{r}
#install.packages("stringr")
#library(stringr)
#df$total_rw <- str_count(df$rw, "\\d+")
```

#Cleaning data tanggal kejadian
```{r}
#Mencari nilai tanggal kejadian yang ""
sum(df$tanggal_kejadian == "")
sum(df$tanggal_kejadian == "0")
sum(df$tanggal_kejadian == "0.0")
# Menampilkan data dengan nilai "0" atau "0.0" di kolom "tanggal_kejadian"
null_tgl <- df[df$tanggal_kejadian %in% c("", "0.0"), ]
null_tgl
# Menghapus data dengan nilai "" atau "0.0" di kolom "tanggal_kejadian"
df_clean <- df[!(df$tanggal_kejadian %in% c("", "0.0")), ]
```
```{r}
sum(df_clean$tanggal_kejadian == "")
sum(df_clean$tanggal_kejadian == "0")
sum(df_clean$tanggal_kejadian == "0.0")
```

```{r}
# Menampilkan data yang memuat kata "" pada kolom "tanggal kejadian"
count(df_clean[grep("\\.", df_clean$tanggal_kejadian), ])
print(df_clean[grep("\\.", df_clean$tanggal_kejadian), ])
```

```{r}
df_clean$tanggal_kejadian <- gsub(" ", "", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("17-29", "17,18,19,20,21,22,23,24,25,26,27,28,29", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("16-29", "16,17,18,19,20,21,22,23,24,25,26,27,28,29", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("25-29", "25,26,27,28,29", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("19-25", "19,20,21,22,23,24,25", df_clean$tanggal_kejadian)

df_clean$tanggal_kejadian <- gsub("1-8", "1,2,3,4,5,6,7,8", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("3-5", "3,4,5", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("16-20", "16,17,18,19,20", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("16-18", "16,17,18", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("17-18", "17,18", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("17-20", "17,18,19,20", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("19-20", "19,20", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("\n", "", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("17-19", "17,18,19", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("10-12", "10,11,12", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("26-27", "26,27", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("10-11", "10,11", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("11-13", "11,12,13", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("19-21", "19,20,21", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("16-21", "16,17,18,19,20,21", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("16-22", "16,17,18,19,20,21,22", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("18-21", "18,19,20,21", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("17-21", "17,18,19,20,21", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("17-22", "17,18,19,20,21,22", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("17-25", "17,18,19,20,21,22,23,24,25", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("16-25", "16,17,18,19,20,21,22,23,24,25", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("22-25", "22,23,24,25", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("23-24", "23,24", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("15-19", "15,16,17,18,19", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("16-19", "16,17,18,19", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("13-14", "13,14", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("18-19", "18,19", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("9-11", "9,10,11", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("09-11", "9,10,11", df_clean$tanggal_kejadian)

df_clean$tanggal_kejadian <- gsub("8-9", "8,9", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("4-5", "4,5", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("5-6", "5,6", df_clean$tanggal_kejadian)

df_clean$tanggal_kejadian <- gsub("1-2", "1,2", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("2-3", "2,3", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("12-13", "12,13", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("1-3", "1,3", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("7-8", "7,8", df_clean$tanggal_kejadian)

df_clean$tanggal_kejadian <- gsub("22-23", "22,23", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("11-12", "11,12", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("1-4", "1,2,3,4", df_clean$tanggal_kejadian)
df_clean$tanggal_kejadian <- gsub("\\(\\)|\\(1Hari\\)|\\(2Hari\\) |\\(2hari\\)|\\(3Hari\\)|\\(1hari\\)|\\(4Hari\\)|\\(5Hari\\)|\\(6Hari\\)|\\(9Hari\\)|s/d|februari|Januari|Oktober|April|tgl|tgl.|TGL|November2020|September|Agustus|Juli|JUNI|MEI|maret|Juli2017|Juni2017|Mei|2020-12-|2020-12\\,|2020-11-|2020-11\\,|\\(2Hari\\)", "", df_clean$tanggal_kejadian)
```

```{r}
print(unique(df_clean$tanggal_kejadian))
```

```{r}
# Membuat kolom baru "total_kejadian"
df_clean$total_kejadian <- sapply(strsplit(df_clean$tanggal_kejadian, ","), function(x) length(x))
```
#CLEANING RW
```{r}
# Mengisi data pada kolom "a" yang berisi "" dengan "0"
df_clean$rw <- replace(df_clean$rw, df_clean$rw == "", "0")
```

```{r}
sum(df_clean$rw == "0")
sum(df_clean$rw == "")
sum(df_clean$ketinggian_air == "0")
sum(df_clean$ketinggian_air == "")
# Menampilkan data dengan nilai "0" atau "0.0" di kolom "tanggal_kejadian"
null_rw <- df_clean[df_clean$rw %in% c("", "0"), ]
null_rw
df_clean <- df_clean[!(df_clean$ketinggian_air %in% c("0")), ]


```
```{r}
unique(df_clean$rw)
```

```{r}

df_clean$rw <- gsub(" ", "", df_clean$rw)
df_clean$rw <- gsub("RW|rw|RW|RW|Rw", "", df_clean$rw)
df_clean$rw <- gsub(":|\\.|", "", df_clean$rw)
df_clean$rw <- gsub("01-017", "01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17", df_clean$rw)
df_clean$rw <- gsub("01-016", "01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16", df_clean$rw)
df_clean$rw <- gsub("01-012", "01,02,03,04,05,06,07,08,09,10,11,12", df_clean$rw)
df_clean$rw <- gsub("01-09", "01,02,03,04,05,06,07,08,09", df_clean$rw)
df_clean$rw <- gsub("01-08", "01,02,03,04,05,06,07,08", df_clean$rw)
df_clean$rw <- gsub("01-07", "01,02,03,04,05,06,07", df_clean$rw)
df_clean$rw <- gsub("01-06", "01,02,03,04,05,06", df_clean$rw)
df_clean$rw <- gsub("01-05", "01,02,03,04,05", df_clean$rw)
df_clean$rw <- gsub("01-04", "01,02,03,04", df_clean$rw)
df_clean$rw <- gsub("01-03", "01,02,03", df_clean$rw)
df_clean$rw <- gsub("01-02", "01,02", df_clean$rw)

df_clean$rw <- gsub("04-012", "04,05,06,07,08,09,10,11,12", df_clean$rw)
df_clean$rw <- gsub("07-10", "07,08,09,10", df_clean$rw)
df_clean$rw <- gsub("04-08", "04,05,06,07,08", df_clean$rw)
df_clean$rw <- gsub("04-07", "04,05,06,07", df_clean$rw)
df_clean$rw <- gsub("04-06", "04,05,06", df_clean$rw)
df_clean$rw <- gsub("03-05", "03,04,05", df_clean$rw)
df_clean$rw <- gsub("4-7", "04,05,06,07", df_clean$rw)
df_clean$rw <- gsub("12-15", "12,13,14,15", df_clean$rw)
df_clean$rw <- gsub("10-14", "10,11,12,13,14", df_clean$rw)
df_clean$rw <- gsub("04-12", "04,05,06,07,08,09,10,11,12", df_clean$rw)
df_clean$rw <- gsub("08-12", "08,09,10,11,12", df_clean$rw)
df_clean$rw <- gsub("11-13", "11,12,13", df_clean$rw)
df_clean$rw <- gsub("02-05", "02,03,04,05", df_clean$rw)

df_clean$rw <- gsub("06-10", "06,07,08,09,10", df_clean$rw)
df_clean$rw <- gsub("07-11", "07,08,09,10,11", df_clean$rw)
df_clean$rw <- gsub("05-07", "05,06,07", df_clean$rw)
df_clean$rw <- gsub("05-08", "05,06,07,08", df_clean$rw)
df_clean$rw <- gsub("05-09", "05,06,07,08,09", df_clean$rw)
df_clean$rw <- gsub("05-10", "05,06,07,08,09,10", df_clean$rw)






```

```{r}
# Menampilkan data yang memuat kata "" pada kolom "ketinggian air"
count(df_clean[grep("-", df_clean$rw), ])
print(df_clean[grep("-", df_clean$rw), ])

```

```{r}
unique(df_clean$rw)
```
```{r}
# Membuat kolom baru "total_rw"
df_clean$total_rw <- sapply(strsplit(df_clean$rw, ","), function(x) length(x))

```

```{r}
# Menyimpan data bersih ke dalam file CSV baru
write.csv(df_clean, file = "data_banjir_clean.csv", row.names = FALSE)
```



